name: cufit
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.0=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - albucore==0.0.17
      - albumentations==1.4.18
      - annotated-types==0.7.0
      - bleach==6.1.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - cmake==4.0.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - efficientnet-pytorch==0.7.1
      - eval-type-backport==0.2.2
      - filelock==3.16.1
      - fire==0.7.0
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - geomloss==0.2.6
      - huggingface-hub==0.30.2
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - joblib==1.4.2
      - kaggle==1.7.4.2
      - kagglehub==0.2.9
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lit==18.1.8
      - llvmlite==0.41.1
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - medmnist==3.0.1
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - munch==4.0.0
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - openai-whisper==20240930
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pandas==2.0.3
      - pillow==10.0.0
      - pretrainedmodels==0.7.4
      - protobuf==5.29.4
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.17.0
      - soundfile==0.13.1
      - sympy==1.13.3
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tiktoken==0.7.0
      - timm==1.0.15
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torchdiffeq==0.2.3
      - torchsampler==0.1.2
      - torchvision==0.19.1+cu121
      - tqdm==4.67.1
      - triton==3.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.2.3
      - webencodings==0.5.1
      - zipp==3.20.2
prefix: /home/work/DATA1/anaconda3/envs/cufit
